#!/bin/sh

port="$(uci -q get gecoosac.config.port)"
changed=0

if [ "$port" != '60650' ]; then
	uci -q set gecoosac.config.port='60650'
	changed=1
fi

[ "$changed" -eq 0 ] || uci -q commit gecoosac

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@gecoosac[-1]
	add ucitrack gecoosac
	set ucitrack.@gecoosac[-1].init=gecoosac
	commit ucitrack
EOF

exit 0
